---
# roles/common/tasks/debian.yml
# applies updates machine, edits hostname and joins to domain
- include_role:
    name: common
    tasks_from: apt_all.yml
- name: Install required packages
  package:
    name: "{{ item }}"
  loop:
    - winbind 
    - libpam-winbind
    - libnss-winbind
    - ntp
  notify: restart ntp
- name: Add winbind to nsswitch.conf
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: "{{ item }}"
    line: \1 winbind
    backrefs: yes
  loop:
    - (^passwd:.*)
    - (^group:.*)
# TODO correct PAM implementation
- name: Insert pam_mkhomedir.sp into /etc/pam.d/common-session
  lineinfile:
    path: /etc/pam.d/common-session
    insertafter: EOF
    line: session optional pam_mkhomedir.so skel=/etc/skel umask=077
- include_role:
    name: winbind_ad_join
    tasks_from: global.yml
- name: Enable services
  service:
    name: ntp
    enabled: yes
- name: Add workgroup, root and wheel groups to sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item }}"
  loop:
    - '# Allowed groups'
    - AllowGroups root sudo "{{ workgroup|upper }}\domain admins"
