---
# Edits firewalld for winbind services and ensures it is enabled
- name: Add services to firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - ntp
    - samba
  notify: 
    - restart firewalld
- name: Enable firewalld
  service:
    name: firewalld
    enabled: yes
