# Provisions Windows instances during the Packer deployment
---
- hosts: default
  become: yes
  become_method: runas
  become_user: Administrator
  tasks:
    - include_role: 
        name: fsecure
        tasks_from: install
    - include_role:
        name: common
        tasks_from: windows_important.yml
    - name: Commands to configure windows
      win_command: "{{ item }}"
      loop:
        - reg.exe ADD HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\ /v HideFileExt /t REG_DWORD /d 0 /f
        - reg.exe ADD HKCU\Console /v QuickEdit /t REG_DWORD /d 1 /f
        - reg.exe ADD HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\ /v StartMenuAdminTools /t REG_DWORD /d 1 /f
        - reg.exe ADD HKLM\SYSTEM\CurrentControlSet\Control\Power\ /v HibernateFileSizePercent /t REG_DWORD /d 0 /f
        - reg.exe ADD HKLM\SYSTEM\CurrentControlSet\Control\Power\ /v HibernateEnabled /t REG_DWORD /d 0 /f
        - reg.exe ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        #- powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        #- powershell.exe Stop-Service -Name wuauserv -Force
        #- powershell.exe Remove-Item c:\Windows\SoftwareDistribution\Download\* -Recurse
    - name: Install chocolatey packages
      win_chocolatey:
        name:
          - notepadplusplus
          - firefox
          - googlechrome
          - 7zip
    - include_role:
        name: update_pwd
        tasks_from: "{{ ansible_os_family|lower }}"
