---
# roles/common/handlers/main.yml
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
- name: restart ntpd
  service:
    name: ntpd
    state: restarted
- name: restart ntp
  service:
    name: ntp
    state: restarted
