# Install updates from M$ and not WSUS
---
- name: Ensure WinRM starts when the system has settled and is ready to work reliably
  win_service:
    name: WinRM
    start_mode: delayed
- name: Install Windows updates and reboot until no new updates are installed
  win_updates:
    server_selection: windows_update
    reboot: yes
    reboot_timeout: 36000
  register: status
  until: status.installed_update_count == 0
  retries: 10
  delay: 1
#   use to see available category names
#    state: searched
#    register: state
# - debug:
#     var: state
