# roles/httpd/tasks/main.yml
---

- name: Install the latest version of Apache
  yum:
    name: httpd
    state: latest
- name: Ensure Apache is enabled
  service:
    name: httpd
    enabled: yes
- name: Install httpd configuration file
  template:
    src: "{{ httpd_config_src }}"
    dest: "{{ httpd_config_dest }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
